apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-ssr-template
  labels:
    app: nextjs-ssr-template
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-ssr-template
  template:
    metadata:
      labels:
        app: nextjs-ssr-template
    spec:
      containers:
        - name: nextjs-ssr-template
          image: your-docker-repo/nextjs-ssr-template:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
